### GET request to example server
POST http://127.0.0.1:3000/api/v1/user/create
Content-Type: application/json

{
  "name": "Maria Oliveira",
  "email": "maria.oliveira1@email.com",
  "document": "987.654.321-00",
  "phone": "+55 21 91234-5678",
  "password": "SenhaSegura456!"
}